// =====================  CANONICAL ROUTE PATHS  ================
export const ROUTES = Object.freeze({
  ROOT: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  UNAUTHORIZED: "/unauthorized",

  // Domain Modules (Modules 2–24)
  USERS: "/users",
  USER_DETAIL: "/users/:id",
  ROLES: "/roles",
  PERMISSIONS: "/permissions",
  BUILDINGS: "/buildings",
  BUILDING_DETAIL: "/buildings/:id",
  BLOCKS: "/blocks",
  FLOORS: "/floors",
  FLATS: "/flats",
  FLAT_DETAIL: "/flats/:id",
  OWNERS: "/owners",
  TENANTS: "/tenants",
  STAFF: "/staff",
  MAINTENANCE_CONFIGURATIONS: "/maintenance-configurations",
  MAINTENANCE_CONFIGURATIONS_HISTORY: "/maintenance-configurations/history",
  MAINTENANCE_REQUESTS: "/maintenance-requests",
  INVOICES: "/invoices",
  INVOICE_DETAIL: "/invoices/:id",
  PAYMENTS: "/payments",
  COMPLAINTS: "/complaints",
  REVIEWS: "/reviews",
  NOTICES: "/notices",
  NOTIFICATIONS: "/notifications",
  EXPENSES: "/expenses",
  VISITORS: "/visitors",
  VISITORS_VERIFY: "/visitors/verify",
  DOCUMENTS: "/documents",
  REPORTS: "/reports",
  AUDIT_LOGS: "/audit-logs",
});
