// =====================  CANONICAL PERMISSIONS  ==============
/**
 * Canonical 44 permission tokens mirroring backend permissions registry
 */
export const PERMISSIONS = Object.freeze({
  // Users
  USER_CREATE: "USER_CREATE",
  USER_READ: "USER_READ",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_STATUS_UPDATE: "USER_STATUS_UPDATE",

  // Roles & Permissions
  ROLE_READ: "ROLE_READ",
  PERMISSION_READ: "PERMISSION_READ",

  // Buildings
  BUILDING_CREATE: "BUILDING_CREATE",
  BUILDING_READ: "BUILDING_READ",
  BUILDING_UPDATE: "BUILDING_UPDATE",
  BUILDING_DELETE: "BUILDING_DELETE",

  // Blocks
  BLOCK_CREATE: "BLOCK_CREATE",
  BLOCK_READ: "BLOCK_READ",
  BLOCK_UPDATE: "BLOCK_UPDATE",
  BLOCK_DELETE: "BLOCK_DELETE",

  // Floors
  FLOOR_CREATE: "FLOOR_CREATE",
  FLOOR_READ: "FLOOR_READ",
  FLOOR_UPDATE: "FLOOR_UPDATE",
  FLOOR_DELETE: "FLOOR_DELETE",

  // Flats
  FLAT_CREATE: "FLAT_CREATE",
  FLAT_READ: "FLAT_READ",
  FLAT_UPDATE: "FLAT_UPDATE",
  FLAT_DELETE: "FLAT_DELETE",

  // Owners
  OWNER_CREATE: "OWNER_CREATE",
  OWNER_READ: "OWNER_READ",
  OWNER_UPDATE: "OWNER_UPDATE",

  // Tenants
  TENANT_CREATE: "TENANT_CREATE",
  TENANT_READ: "TENANT_READ",
  TENANT_UPDATE: "TENANT_UPDATE",
  TENANT_DELETE: "TENANT_DELETE",

  // Staff
  STAFF_CREATE: "STAFF_CREATE",
  STAFF_READ: "STAFF_READ",
  STAFF_UPDATE: "STAFF_UPDATE",

  // Maintenance Config
  CONFIG_CREATE: "CONFIG_CREATE",
  CONFIG_READ: "CONFIG_READ",
  CONFIG_UPDATE: "CONFIG_UPDATE",

  // Maintenance Requests
  REQUEST_CREATE: "REQUEST_CREATE",
  REQUEST_READ: "REQUEST_READ",
  REQUEST_UPDATE: "REQUEST_UPDATE",
  REQUEST_ASSIGN: "REQUEST_ASSIGN",

  // Invoices & Billing
  INVOICE_GENERATE: "INVOICE_GENERATE",
  INVOICE_READ: "INVOICE_READ",
  INVOICE_UPDATE: "INVOICE_UPDATE",

  // Payments
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_READ: "PAYMENT_READ",
  PAYMENT_UPDATE: "PAYMENT_UPDATE",

  // Complaints
  COMPLAINT_CREATE: "COMPLAINT_CREATE",
  COMPLAINT_READ: "COMPLAINT_READ",
  COMPLAINT_TRIAGE: "COMPLAINT_TRIAGE",
  COMPLAINT_ASSIGN: "COMPLAINT_ASSIGN",
  COMPLAINT_RESOLVE: "COMPLAINT_RESOLVE",

  // Reviews
  REVIEW_CREATE: "REVIEW_CREATE",
  REVIEW_READ: "REVIEW_READ",
  REVIEW_MODERATE: "REVIEW_MODERATE",

  // Notices
  NOTICE_CREATE: "NOTICE_CREATE",
  NOTICE_READ: "NOTICE_READ",
  NOTICE_RETRACT: "NOTICE_RETRACT",

  // Notifications
  NOTIFICATION_READ: "NOTIFICATION_READ",

  // Expenses
  EXPENSE_CREATE: "EXPENSE_CREATE",
  EXPENSE_READ: "EXPENSE_READ",
  EXPENSE_APPROVE: "EXPENSE_APPROVE",

  // Visitors
  VISITOR_CREATE: "VISITOR_CREATE",
  VISITOR_READ: "VISITOR_READ",
  VISITOR_VERIFY: "VISITOR_VERIFY",

  // Documents
  DOCUMENT_UPLOAD: "DOCUMENT_UPLOAD",
  DOCUMENT_READ: "DOCUMENT_READ",
  DOCUMENT_DELETE: "DOCUMENT_DELETE",

  // Reports
  REPORT_READ: "REPORT_READ",

  // Audit Logs
  AUDIT_LOG_READ: "AUDIT_LOG_READ",
});
