// =====================  STATUS SEMANTIC CATEGORIES & MAP (SECTION 41 & APPENDIX §A.1)  =====

/**
 * 5 Canonical Semantic Categories & Color Pairs (Appendix §A.1)
 */
export const SEMANTIC_CATEGORIES = Object.freeze({
  NEUTRAL_PENDING: "NEUTRAL_PENDING",
  IN_PROGRESS_ACTIVE: "IN_PROGRESS_ACTIVE",
  RESOLVED_POSITIVE: "RESOLVED_POSITIVE",
  ATTENTION_OVERDUE: "ATTENTION_OVERDUE",
  REJECTED_NEGATIVE: "REJECTED_NEGATIVE",
});

/**
 * Semantic Color Pairs for Light & Dark modes
 */
export const SEMANTIC_STYLES = Object.freeze({
  light: {
    [SEMANTIC_CATEGORIES.NEUTRAL_PENDING]: {
      color: "#8A8578",
      backgroundColor: "#EFEBE0",
      border: "1px solid rgba(138, 133, 120, 0.2)",
    },
    [SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE]: {
      color: "#2E5C8A", // info.600
      backgroundColor: "#E7EEF6",
      border: "1px solid rgba(46, 92, 138, 0.2)",
    },
    [SEMANTIC_CATEGORIES.RESOLVED_POSITIVE]: {
      color: "#2E7D5B", // evergreen.600
      backgroundColor: "#E4EFE8",
      border: "1px solid rgba(46, 125, 91, 0.2)",
    },
    [SEMANTIC_CATEGORIES.ATTENTION_OVERDUE]: {
      color: "#B7791F", // warning.600
      backgroundColor: "#F6EEDF",
      border: "1px solid rgba(183, 121, 31, 0.2)",
    },
    [SEMANTIC_CATEGORIES.REJECTED_NEGATIVE]: {
      color: "#B3261E", // danger.600
      backgroundColor: "#F6E7E5",
      border: "1px solid rgba(179, 38, 30, 0.2)",
    },
  },
  dark: {
    [SEMANTIC_CATEGORIES.NEUTRAL_PENDING]: {
      color: "#D6D1C4",
      backgroundColor: "#2E2C26",
      border: "1px solid rgba(214, 209, 196, 0.2)",
    },
    [SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE]: {
      color: "#8AB4F8",
      backgroundColor: "#172A42",
      border: "1px solid rgba(138, 180, 248, 0.2)",
    },
    [SEMANTIC_CATEGORIES.RESOLVED_POSITIVE]: {
      color: "#81C995",
      backgroundColor: "#133526",
      border: "1px solid rgba(129, 201, 149, 0.2)",
    },
    [SEMANTIC_CATEGORIES.ATTENTION_OVERDUE]: {
      color: "#FDD663",
      backgroundColor: "#423214",
      border: "1px solid rgba(253, 214, 99, 0.2)",
    },
    [SEMANTIC_CATEGORIES.REJECTED_NEGATIVE]: {
      color: "#F28B82",
      backgroundColor: "#421815",
      border: "1px solid rgba(242, 139, 130, 0.2)",
    },
  },
});

/**
 * Maps every system status to exactly one of the 5 canonical semantic categories
 */
export const STATUS_TO_SEMANTIC_MAP = Object.freeze({
  // Neutral / pending: PENDING, DRAFT, INACTIVE, EXPECTED, ON_LEAVE
  PENDING: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  DRAFT: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  INACTIVE: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  EXPECTED: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  ON_LEAVE: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  PENDING_APPROVAL: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  UNDER_CONSTRUCTION: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,

  // In progress / active: ACTIVE, OCCUPIED, OPEN, ASSIGNED, IN_PROGRESS, UNDER_MAINTENANCE, TRIAGED, UNDER_INVESTIGATION, CHECKED_IN
  ACTIVE: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  OCCUPIED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  OPEN: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  ASSIGNED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  IN_PROGRESS: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  UNDER_MAINTENANCE: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  TRIAGED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  UNDER_INVESTIGATION: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  CHECKED_IN: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  PARTIALLY_PAID: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  ISSUED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,

  // Resolved / positive: COMPLETED, PAID, APPROVED, VACANT, VERIFIED, RESOLVED, PUBLISHED, CHECKED_OUT, CLOSED
  COMPLETED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  PAID: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  APPROVED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  VACANT: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  VERIFIED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  RESOLVED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  PUBLISHED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  CHECKED_OUT: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  CLOSED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,

  // Attention / overdue: OVERDUE, SUSPENDED, FLAGGED
  OVERDUE: SEMANTIC_CATEGORIES.ATTENTION_OVERDUE,
  SUSPENDED: SEMANTIC_CATEGORIES.ATTENTION_OVERDUE,
  FLAGGED: SEMANTIC_CATEGORIES.ATTENTION_OVERDUE,

  // Rejected / negative: REJECTED, CANCELLED, VOID, TERMINATED, DENIED, EXPIRED, HIDDEN, MOVED_OUT
  REJECTED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  CANCELLED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  VOID: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  TERMINATED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  DENIED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  EXPIRED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  HIDDEN: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  MOVED_OUT: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
});
