// =====================  STATUS SEMANTIC CATEGORIES & MAP (SECTION 41 & APPENDIX §A.1)  =====

/**
 * 5 Canonical Semantic Categories & Color Pairs (Appendix §A.1)
 */
export const SEMANTIC_CATEGORIES = Object.freeze({
  NEUTRAL_PENDING: "NEUTRAL_PENDING",
  IN_PROGRESS_ACTIVE: "IN_PROGRESS_ACTIVE",
  RESOLVED_POSITIVE: "RESOLVED_POSITIVE",
  ATTENTION_OVERDUE: "ATTENTION_OVERDUE",
  REJECTED_NEGATIVE: "REJECTED_NEGATIVE",
});

/**
 * Semantic Color Pairs for Light & Dark modes (Appendix §A.1)
 */
export const SEMANTIC_STYLES = Object.freeze({
  light: {
    [SEMANTIC_CATEGORIES.NEUTRAL_PENDING]: {
      color: "#64748B", // text.secondary
      backgroundColor: "#F1F5F9",
      border: "1px solid #E2E8F0",
    },
    [SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE]: {
      color: "#4338CA", // brand.600
      backgroundColor: "#EEF2FF", // soft brand.50/100
      border: "1px solid #C7D2FE",
    },
    [SEMANTIC_CATEGORIES.RESOLVED_POSITIVE]: {
      color: "#15803D", // accent.green dark
      backgroundColor: "#DCFCE7",
      border: "1px solid #BBF7D0",
    },
    [SEMANTIC_CATEGORIES.ATTENTION_OVERDUE]: {
      color: "#B45309", // accent.amber dark
      backgroundColor: "#FEF3C7",
      border: "1px solid #FDE68A",
    },
    [SEMANTIC_CATEGORIES.REJECTED_NEGATIVE]: {
      color: "#DC2626", // danger.600
      backgroundColor: "#FEE2E2",
      border: "1px solid #FECACA",
    },
  },
  dark: {
    [SEMANTIC_CATEGORIES.NEUTRAL_PENDING]: {
      color: "#94A3B8",
      backgroundColor: "#1E293B",
      border: "1px solid #334155",
    },
    [SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE]: {
      color: "#A5B4FC",
      backgroundColor: "#1E1B4B",
      border: "1px solid #3730A3",
    },
    [SEMANTIC_CATEGORIES.RESOLVED_POSITIVE]: {
      color: "#86EFAC",
      backgroundColor: "#064E3B",
      border: "1px solid #059669",
    },
    [SEMANTIC_CATEGORIES.ATTENTION_OVERDUE]: {
      color: "#FDE047",
      backgroundColor: "#78350F",
      border: "1px solid #B45309",
    },
    [SEMANTIC_CATEGORIES.REJECTED_NEGATIVE]: {
      color: "#FCA5A5",
      backgroundColor: "#7F1D1D",
      border: "1px solid #DC2626",
    },
  },
});

/**
 * Maps every system status to exactly one of the 5 canonical semantic categories
 */
export const STATUS_TO_SEMANTIC_MAP = Object.freeze({
  // Neutral / pending: PENDING, DRAFT, INACTIVE, EXPECTED, ON_LEAVE
  PENDING: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  DRAFT: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  INACTIVE: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  EXPECTED: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  ON_LEAVE: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  PENDING_APPROVAL: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,
  UNDER_CONSTRUCTION: SEMANTIC_CATEGORIES.NEUTRAL_PENDING,

  // In progress / active: ACTIVE, OCCUPIED, OPEN, ASSIGNED, IN_PROGRESS, UNDER_MAINTENANCE, TRIAGED, UNDER_INVESTIGATION, CHECKED_IN
  ACTIVE: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  OCCUPIED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  OPEN: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  ASSIGNED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  IN_PROGRESS: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  UNDER_MAINTENANCE: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  TRIAGED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  UNDER_INVESTIGATION: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  CHECKED_IN: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  PARTIALLY_PAID: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,
  ISSUED: SEMANTIC_CATEGORIES.IN_PROGRESS_ACTIVE,

  // Resolved / positive: COMPLETED, PAID, APPROVED, VACANT, VERIFIED, RESOLVED, PUBLISHED, CHECKED_OUT, CLOSED
  COMPLETED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  PAID: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  APPROVED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  VACANT: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  VERIFIED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  RESOLVED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  PUBLISHED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  CHECKED_OUT: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,
  CLOSED: SEMANTIC_CATEGORIES.RESOLVED_POSITIVE,

  // Attention / overdue: OVERDUE, SUSPENDED, FLAGGED
  OVERDUE: SEMANTIC_CATEGORIES.ATTENTION_OVERDUE,
  SUSPENDED: SEMANTIC_CATEGORIES.ATTENTION_OVERDUE,
  FLAGGED: SEMANTIC_CATEGORIES.ATTENTION_OVERDUE,

  // Rejected / negative: REJECTED, CANCELLED, VOID, TERMINATED, DENIED, EXPIRED, HIDDEN, MOVED_OUT
  REJECTED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  CANCELLED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  VOID: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  TERMINATED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  DENIED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  EXPIRED: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  HIDDEN: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
  MOVED_OUT: SEMANTIC_CATEGORIES.REJECTED_NEGATIVE,
});
