// =====================  RBAC & OBAC UTILITIES  ==============
import { ROLES } from "../constants/roles.js";
import { PERMISSIONS } from "../constants/permissions.js";

/**
 * Static baseline permission map matching backend role definitions
 */
export const ROLE_PERMISSIONS_MAP = Object.freeze({
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),

  [ROLES.BUILDING_ADMIN]: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_STATUS_UPDATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.PERMISSION_READ,
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.BUILDING_UPDATE,
    PERMISSIONS.BLOCK_CREATE,
    PERMISSIONS.BLOCK_READ,
    PERMISSIONS.BLOCK_UPDATE,
    PERMISSIONS.BLOCK_DELETE,
    PERMISSIONS.FLOOR_CREATE,
    PERMISSIONS.FLOOR_READ,
    PERMISSIONS.FLOOR_UPDATE,
    PERMISSIONS.FLOOR_DELETE,
    PERMISSIONS.FLAT_CREATE,
    PERMISSIONS.FLAT_READ,
    PERMISSIONS.FLAT_UPDATE,
    PERMISSIONS.FLAT_DELETE,
    PERMISSIONS.OWNER_CREATE,
    PERMISSIONS.OWNER_READ,
    PERMISSIONS.OWNER_UPDATE,
    PERMISSIONS.TENANT_CREATE,
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.TENANT_DELETE,
    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.CONFIG_CREATE,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.CONFIG_UPDATE,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_READ,
    PERMISSIONS.REQUEST_UPDATE,
    PERMISSIONS.REQUEST_ASSIGN,
    PERMISSIONS.INVOICE_GENERATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_READ,
    PERMISSIONS.COMPLAINT_TRIAGE,
    PERMISSIONS.COMPLAINT_ASSIGN,
    PERMISSIONS.COMPLAINT_RESOLVE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.REVIEW_MODERATE,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTICE_RETRACT,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.VISITOR_CREATE,
    PERMISSIONS.VISITOR_READ,
    PERMISSIONS.VISITOR_VERIFY,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.AUDIT_LOG_READ,
  ],

  [ROLES.MANAGER]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.BLOCK_READ,
    PERMISSIONS.FLOOR_READ,
    PERMISSIONS.FLAT_READ,
    PERMISSIONS.OWNER_READ,
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.STAFF_READ,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_READ,
    PERMISSIONS.REQUEST_UPDATE,
    PERMISSIONS.REQUEST_ASSIGN,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_READ,
    PERMISSIONS.COMPLAINT_TRIAGE,
    PERMISSIONS.COMPLAINT_ASSIGN,
    PERMISSIONS.COMPLAINT_RESOLVE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.NOTICE_CREATE,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.VISITOR_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.REPORT_READ,
  ],

  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.FLAT_READ,
    PERMISSIONS.OWNER_READ,
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.CONFIG_READ,
    PERMISSIONS.INVOICE_GENERATE,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_UPDATE,
    PERMISSIONS.EXPENSE_CREATE,
    PERMISSIONS.EXPENSE_READ,
    PERMISSIONS.EXPENSE_APPROVE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.REPORT_READ,
  ],

  [ROLES.MAINTENANCE_STAFF]: [
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.FLAT_READ,
    PERMISSIONS.REQUEST_READ,
    PERMISSIONS.REQUEST_UPDATE,
    PERMISSIONS.NOTIFICATION_READ,
  ],

  [ROLES.SECURITY_STAFF]: [
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.FLAT_READ,
    PERMISSIONS.VISITOR_CREATE,
    PERMISSIONS.VISITOR_READ,
    PERMISSIONS.VISITOR_VERIFY,
    PERMISSIONS.NOTIFICATION_READ,
  ],

  [ROLES.OWNER]: [
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.FLAT_READ,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_READ,
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.VISITOR_CREATE,
    PERMISSIONS.VISITOR_READ,
    PERMISSIONS.DOCUMENT_READ,
  ],

  [ROLES.TENANT]: [
    PERMISSIONS.BUILDING_READ,
    PERMISSIONS.FLAT_READ,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_READ,
    PERMISSIONS.INVOICE_READ,
    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_READ,
    PERMISSIONS.REVIEW_CREATE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.NOTICE_READ,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.VISITOR_CREATE,
    PERMISSIONS.VISITOR_READ,
    PERMISSIONS.DOCUMENT_READ,
  ],
});

export const hasPermission = (user, permission) => {
  if (!user || !user.role) return false;
  if (user.role === ROLES.SUPER_ADMIN) return true;

  if (Array.isArray(user.permissions) && user.permissions.length > 0) {
    return user.permissions.includes(permission);
  }

  const rolePermissions = ROLE_PERMISSIONS_MAP[user.role] || [];
  return rolePermissions.includes(permission);
};

export const hasAnyPermission = (user, permissions = []) => {
  if (!user || !user.role) return false;
  if (user.role === ROLES.SUPER_ADMIN) return true;
  return permissions.some((perm) => hasPermission(user, perm));
};

export const hasAllPermissions = (user, permissions = []) => {
  if (!user || !user.role) return false;
  if (user.role === ROLES.SUPER_ADMIN) return true;
  return permissions.every((perm) => hasPermission(user, perm));
};

export const hasRole = (user, allowedRoles = []) => {
  if (!user || !user.role) return false;
  return allowedRoles.includes(user.role);
};

export const canAccessBuilding = (user, buildingId) => {
  if (!user) return false;
  if (user.role === ROLES.SUPER_ADMIN) return true;
  if (!buildingId) return true;

  const assigned = user.assignedBuildingIds || [];
  return assigned.includes(buildingId);
};
